version: '3'

services:
  main:
    container_name: note-main
    build:
      context: .
    ports:
      - 80:3000
    depends_on:
      - postgres
    env_file:
      - .env.docker

  postgres:
    image: postgres:14
    container_name: note-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.docker
    volumes:
      - ./:/docker-entrypoint-initdb.d
