version: '3'

services:
  backend:
    container_name: note-backend
    restart: always
    environment:
      NODE_ENV: production
      DATABASE: 'docker.sqlite'
      PORT: 3000
      PER_PAGE: 15
      SWAGGER_PREFIX: http://localhost/api
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - backend
  frontend:
    container_name: note-frontend
    environment:
      NODE_ENV: production
      VITE_API_URL: /api/
    depends_on:
      - backend
    ports:
    - 80:80
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - backend

networks:
  backend:
    driver: bridge
