FROM node:16 AS builder
WORKDIR /app
COPY . .
RUN npm ci -w @severstal-test/frontend --include-workspace-root
RUN npm run build -w @severstal-test/frontend

FROM nginx:1.23.0-alpine
COPY --from=builder /app/packages/frontend/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
